"""Compile and inspect documented project-local settings, without claiming runtime enforcement."""
from pathlib import Path
import tomlkit
from agentignore.policy import matches

PROFILE = 'agentignore'
LIMITATIONS = [
    'Static project-local configuration check only; runtime enforcement is not verified.',
    'Codex: trust, user/managed settings, CLI overrides and legacy sandbox settings can change the effective policy. Permission profiles are beta.',
    'Codex deny rules cover sandboxed local commands; MCP, connectors, cloud tasks and approved escalations have separate controls.',
    'Glob expansion can be platform-dependent; verify with harmless canary files after restarting the client.',
    'The file audit skips VCS and .codex configuration directories. Deep scanning skips binary files, files over 1 MB and lines over 5000 characters. It is not a complete secret scanner.',
]


def load_config(path: Path, kind: str):
    if kind != 'codex':
        raise ValueError('Only Codex is supported')
    if path.is_symlink() or path.parent.is_symlink():
        raise ValueError(f'Refusing symlink config: {path}')
    if not path.exists():
        return tomlkit.document()
    text = path.read_text(encoding='utf-8')
    text = text.removeprefix('# Managed profile: agentignore (generated by agentignore)\n')
    value = tomlkit.parse(text)
    if not isinstance(value, dict):
        raise ValueError(f'{path}: configuration must be an object/table')
    return value


def _object(parent, key):
    value = parent.setdefault(key, {})
    if not isinstance(value, dict):
        raise ValueError(f'{key} must be an object/table')
    return value


def compile_codex(config, patterns, *, owned=False):
    if any(key in config for key in ('sandbox_mode', 'sandbox_workspace_write')):
        raise ValueError('Codex legacy sandbox settings conflict with permission profiles; migrate them explicitly first')
    selected = config.get('default_permissions')
    if selected not in (None, PROFILE):
        raise ValueError(f'Codex selects {selected!r}; refusing to replace an existing permission profile')
    permissions = _object(config, 'permissions')
    if PROFILE in permissions and not owned:
        # The marker is a comment instead of an unknown Codex config key (see syncer).
        raise ValueError('Reserved profile agentignore already exists without an ownership marker')
    profile = permissions.setdefault(PROFILE, {'extends': ':workspace'})
    if not isinstance(profile, dict) or profile.get('extends') not in (':workspace', ':read-only'):
        raise ValueError('Managed Codex profile must extend :workspace or :read-only')
    fs = _object(profile, 'filesystem')
    fs.setdefault('glob_scan_max_depth', 20)
    depth = fs['glob_scan_max_depth']
    if not isinstance(depth, int) or isinstance(depth, bool) or depth < 1:
        raise ValueError('glob_scan_max_depth must be a positive integer')
    scoped = _object(fs, ':workspace_roots')
    if any(access != 'deny' for access in scoped.values()):
        raise ValueError('Managed Codex profile contains read/write overrides; review them explicitly')
    for pattern in patterns:
        scoped[pattern] = 'deny'
    config['default_permissions'] = PROFILE
    return '# Managed profile: agentignore (generated by agentignore)\n' + tomlkit.dumps(config)


def configured_patterns(repo_path: Path, target: str):
    from agentignore.constants import TARGET_FILENAME_MAP
    path = repo_path / TARGET_FILENAME_MAP[target]
    config = load_config(path, target)
    if any(key in config for key in ('sandbox_mode', 'sandbox_workspace_write')):
        raise ValueError('Codex legacy sandbox settings override permission profiles')
    selected = config.get('default_permissions')
    profile = config.get('permissions', {}).get(selected, {}) if selected else {}
    if selected and selected not in (':workspace', ':read-only') and not profile:
        raise ValueError('Selected Codex permission profile is undefined')
    # This inspector only models profiles based directly on the documented built-ins.
    if profile and profile.get('extends') not in (':workspace', ':read-only'):
        raise ValueError('Codex profile inheritance is not modeled; effective policy is unknown')
    fs = profile.get('filesystem', {})
    if any(key not in ('glob_scan_max_depth', ':workspace_roots') for key in fs):
        raise ValueError('Codex direct filesystem overrides are not modeled; effective policy is unknown')
    scoped = fs.get(':workspace_roots', {})
    if not isinstance(scoped, dict):
        raise ValueError('Codex workspace filesystem must be a table')
    if any(v != 'deny' for v in scoped.values()):
        raise ValueError('Codex mixed read/write/deny overrides require runtime verification')
    # Exact directory rules deny descendants; globs remain slash-aware.
    patterns = [p for p, access in scoped.items() if access == 'deny']
    return patterns + [p.rstrip('/') + '/**' for p in patterns if '*' not in p and '?' not in p]


def covers(patterns, path: str):
    return any(matches(p, path) for p in patterns)
