"""Git hook manager for automated pre-commit shielding."""

import os
from pathlib import Path
from typing import Tuple

PRE_COMMIT_SCRIPT = """#!/bin/sh
# Auto-generated by agentignore (https://github.com/ada-yq225/agentignore)
# Universal AI Context Shield Pre-Commit Hook

echo "🛡️  Running agentignore pre-commit audit..."
if command -v agentignore >/dev/null 2>&1; then
    agentignore check --strict
elif [ -f "./.venv/bin/agentignore" ]; then
    ./.venv/bin/agentignore check --strict
else
    python3 -m agentignore.cli check --strict
fi

RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "❌ agentignore: Context leak detected! Commit blocked to prevent secret leaks or token bloat."
    echo "💡 Run 'agentignore sync' to resolve, or commit with --no-verify to bypass."
    exit 1
fi
exit 0
"""


def install_pre_commit_hook(repo_path: Path) -> Tuple[bool, str]:
    """Install git pre-commit hook to block commits with AI context leaks."""
    git_dir = repo_path / ".git"
    if not git_dir.exists() or not git_dir.is_dir():
        return False, "Not a git repository (missing .git directory)"

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    hook_file = hooks_dir / "pre-commit"
    hook_file.write_text(PRE_COMMIT_SCRIPT, encoding="utf-8")

    # Make executable on Unix
    try:
        current_mode = os.stat(hook_file).st_mode
        os.chmod(hook_file, current_mode | 0o755)
    except OSError:
        pass

    return True, str(hook_file)


def uninstall_pre_commit_hook(repo_path: Path) -> Tuple[bool, str]:
    """Remove agentignore git pre-commit hook."""
    hook_file = repo_path / ".git" / "hooks" / "pre-commit"
    if not hook_file.exists():
        return False, "No pre-commit hook found"

    try:
        content = hook_file.read_text(encoding="utf-8", errors="ignore")
        if "agentignore" in content:
            hook_file.unlink()
            return True, str(hook_file)
        else:
            return False, "Existing pre-commit hook was not created by agentignore"
    except OSError as e:
        return False, str(e)
