"""Preflight all changes, then merge project-local Codex and Claude settings."""
from pathlib import Path
from dataclasses import dataclass
import os
import stat
from agentignore.constants import TARGET_FILENAME_MAP
from agentignore.policy import read_policy
from agentignore.adapters import compile_claude, compile_codex, configured_patterns, load_config


def validate_targets(targets=None):
    targets = list(TARGET_FILENAME_MAP) if targets is None else targets
    if not targets or any(t not in TARGET_FILENAME_MAP for t in targets):
        raise ValueError('Supported targets: codex, claude')
    return list(dict.fromkeys(targets))


@dataclass
class PlannedChange:
    path: Path
    content: str
    status: str
    added_permissions: list

    def summary(self, root):
        return dict(path=str(self.path.relative_to(root)), status=self.status,
                    added_permissions=self.added_permissions)


def _permission_entries(config, target):
    if target == 'claude':
        return config.get('permissions', {}).get('deny', [])
    scope = config.get('permissions', {}).get('agentignore', {}).get('filesystem', {}).get(':workspace_roots', {})
    return [pattern for pattern, access in scope.items() if access == 'deny']


def plan_repository(repo_path: Path, targets=None, dry_run=False, include_lockfiles=False):
    from agentignore.project import load_settings
    targets = validate_targets(targets if targets is not None else load_settings(repo_path).targets)
    patterns = read_policy(repo_path, include_lockfiles)
    planned = []
    for target in targets:
        path = repo_path / TARGET_FILENAME_MAP[target]
        if path.parent.is_symlink():
            raise ValueError(f'Refusing symlink config directory: {path.parent}')
        config = load_config(path, target)
        before = load_config(path, target)
        backup = path.with_name(path.name + '.agentignore.bak')
        if backup.is_symlink():
            raise ValueError(f'Refusing symlink backup: {backup}')
        old = path.read_text(encoding='utf-8') if path.exists() else None
        if target == 'codex':
            owned = bool(old and old.startswith('# Managed profile: agentignore (generated by agentignore)\n'))
            content = compile_codex(config, patterns, owned=owned)
        else:
            content = compile_claude(config, patterns)
        added = sorted(set(_permission_entries(config, target)) - set(_permission_entries(before, target)))
        planned.append(PlannedChange(path, content, 'unchanged' if old == content else 'updated' if old is not None else 'created', added))
    return planned


def sync_repository(repo_path: Path, targets=None, dry_run=False, include_lockfiles=False):
    planned = plan_repository(repo_path, targets, dry_run, include_lockfiles)
    # Malformed inputs / conflicts fail before any settings file is written.
    if not dry_run:
        for change in planned:
            path, content, status = change.path, change.content, change.status
            if status == 'unchanged':
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o600
            if path.exists():
                backup = path.with_name(path.name + '.agentignore.bak')
                if not backup.exists():
                    with backup.open('xb') as stream:
                        os.chmod(backup, mode)
                        stream.write(path.read_bytes())
            temp = path.with_name(path.name + '.agentignore.tmp')
            with temp.open('x', encoding='utf-8') as stream:
                os.chmod(temp, mode)
                stream.write(content)
            temp.replace(path)
    return {str(change.path.relative_to(repo_path)): change.status for change in planned}


def compute_ignore_diff(repo_path: Path, target_key='codex'):
    validate_targets([target_key])
    expected = set(read_policy(repo_path))
    actual = set(configured_patterns(repo_path, target_key))
    actual = {p for p in actual if not (p.endswith('/**') and p[:-3] in actual)}
    return {'missing_in_ai': sorted(expected - actual), 'unique_in_ai': sorted(actual - expected)}
